### ISSUE TITLE
Petite erreur sur la police Luciole

### ISSUE THREAD

**Issue by juliemoynat** [emma11y/sous-titres#2]
Salut,

Tu dis dans ta page :

> Le DINIUM a créé [la police Luciole](http://luciole-vision.com/) qui est disponible gratuitement. Vous pouvez l'utiliser si vous créez des sous-titres et les incrustez sur une vidéo.

J'imagine que tu parles de la DINUM ? Pour info, elle n'a rien à voir avec la création de cette police qui a été créée par Laurent Bourcellier et Jonathan Perez. Elle est, je cite l'introduction du site, "le résultat de plus de deux années de collaboration entre le Centre Technique Régional pour la Déficience Visuelle et le studio typographies.fr".

Cette phrase pourrait donc être reformulée ainsi, par exemple :

> Si vous incrustez les sous-titres dans une vidéo, vous pouvez également utiliser gratuitement [la police Luciole](http://luciole-vision.com/), résultat d'une collaboration entre le Centre Technique Régional pour la Déficience Visuelle et le studio typographies.fr.

**Comment by emma11y** [comment]
Merci @juliemoynat. J'ai enfin pris le temps de mettre à jour mon document. Je suis désolée d'avoir tardé. ;-)

**Comment by emma11y** [comment]
Je close l'issue.
